# Guidance rendering helpers.

source_guidance() { printf '%s/.agents/global/instructions.md\n' "$AGENT_TOOLKIT_HOME"; }
agent_toolkit_start='<!-- agent-toolkit:start -->'
agent_toolkit_end='<!-- agent-toolkit:end -->'
agent_toolkit_notice='<!-- This configuration block is auto-generated by the agent-toolkit repository; manual edits may be overwritten. -->'
concise_output_start='<!-- agent-toolkit:concise-output:start -->'
concise_output_end='<!-- agent-toolkit:concise-output:end -->'
has_concise_output_block() {
  grep -Fxq "$concise_output_start" "$1" && grep -Fxq "$concise_output_end" "$1"
}
update_concise_output_block() {
  local destination=$1 temp
  temp="$(mktemp "${destination}.XXXXXX")"
  cp -p "$destination" "$temp"
  awk -v start="$concise_output_start" -v end="$concise_output_end" '
    $0 == start { in_block = 1; next }
    $0 == end { in_block = 0; next }
    !in_block { print }
  ' "$destination" > "$temp"
  if [[ "$CONCISE_OUTPUT" == true ]]; then
    cat >> "$temp" <<EOF

$concise_output_start
## Concise output

Apply the installed \`concise-output\` skill to all reader-facing responses,
including explanations, reviews, tickets, and documentation.
$concise_output_end
EOF
  fi
  mv "$temp" "$destination"
}
render_guidance_block() {
  local destination=$1 temp
  cp "$(source_guidance)" "$destination"
  update_concise_output_block "$destination"
  temp="$(mktemp "${destination}.XXXXXX")"
  {
    printf '%s\n' "$agent_toolkit_start"
    printf '%s\n\n' "$agent_toolkit_notice"
    cat "$destination"
    printf '\n%s\n' "$agent_toolkit_end"
  } > "$temp"
  mv "$temp" "$destination"
}
strip_guidance_blocks() {
  local destination=$1 temp
  temp="$(mktemp "${destination}.XXXXXX")"
  awk -v guidance_start="$agent_toolkit_start" \
      -v guidance_end="$agent_toolkit_end" \
      -v concise_start="$concise_output_start" \
      -v concise_end="$concise_output_end" '
    $0 == guidance_start || $0 == concise_start { block_depth++; next }
    ($0 == guidance_end || $0 == concise_end) && block_depth > 0 {
      block_depth--
      next
    }
    block_depth == 0 { print }
  ' "$destination" > "$temp"
  mv "$temp" "$destination"
}
append_guidance() {
  local destination=$1 block
  block="$(mktemp "${destination}.XXXXXX")"
  render_guidance_block "$block"
  strip_guidance_blocks "$destination"
  cat "$block" >> "$destination"
  rm -f "$block"
}
render_guidance() { render_guidance_block "$1"; }
