#!/usr/bin/env bash

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
AGENT_TOOLKIT_HOME="${AGENT_TOOLKIT_HOME:-$(cd "$SCRIPT_DIR/.." && pwd)}"

# Configuration

load_provider() {
  if [[ -z "${LLM_PROVIDER+x}" && -f "$AGENT_TOOLKIT_HOME/.env" ]]; then
    while IFS= read -r line || [[ -n "$line" ]]; do
      [[ "$line" =~ ^[[:space:]]*LLM_PROVIDER[[:space:]]*=[[:space:]]*(.*)[[:space:]]*$ ]] || continue
      LLM_PROVIDER="${BASH_REMATCH[1]}"
      LLM_PROVIDER="${LLM_PROVIDER#\"}"; LLM_PROVIDER="${LLM_PROVIDER%\"}"
      LLM_PROVIDER="${LLM_PROVIDER#\'}"; LLM_PROVIDER="${LLM_PROVIDER%\'}"
      export LLM_PROVIDER
      break
    done < "$AGENT_TOOLKIT_HOME/.env"
  fi
  if [[ -z "${LLM_PROVIDER:-}" ]]; then
    echo "Error: LLM_PROVIDER is required; set it in .env or the environment (codex or claude)." >&2
    return 1
  fi
  case "$LLM_PROVIDER" in
    codex|claude) ;;
    *) echo "Error: invalid LLM_PROVIDER '$LLM_PROVIDER'; expected codex or claude." >&2; return 1 ;;
  esac
}

load_concise_output() {
  if [[ -z "${CONCISE_OUTPUT+x}" && -f "$AGENT_TOOLKIT_HOME/.env" ]]; then
    while IFS= read -r line || [[ -n "$line" ]]; do
      [[ "$line" =~ ^[[:space:]]*CONCISE_OUTPUT[[:space:]]*=[[:space:]]*(.*)[[:space:]]*$ ]] || continue
      CONCISE_OUTPUT="${BASH_REMATCH[1]}"
      CONCISE_OUTPUT="${CONCISE_OUTPUT#\"}"; CONCISE_OUTPUT="${CONCISE_OUTPUT%\"}"
      CONCISE_OUTPUT="${CONCISE_OUTPUT#\'}"; CONCISE_OUTPUT="${CONCISE_OUTPUT%\'}"
      export CONCISE_OUTPUT
      break
    done < "$AGENT_TOOLKIT_HOME/.env"
  fi
  CONCISE_OUTPUT="${CONCISE_OUTPUT:-True}"
  case "$(printf '%s' "$CONCISE_OUTPUT" | tr '[:upper:]' '[:lower:]')" in
    true|1|yes|on) CONCISE_OUTPUT=true ;;
    false|0|no|off) CONCISE_OUTPUT=false ;;
    *) echo "Error: invalid CONCISE_OUTPUT '$CONCISE_OUTPUT'; expected true or false." >&2; return 1 ;;
  esac
  export CONCISE_OUTPUT
}

load_config() {
  load_provider
  load_concise_output
}

# Provider integration

provider_skills_dest() {
  case "$LLM_PROVIDER" in
    codex) printf '%s/skills/agent-toolkit\n' "${AGENTS_HOME:-$HOME/.agents}" ;;
    claude) printf '%s/skills\n' "${CLAUDE_HOME:-$HOME/.claude}" ;;
  esac
}

provider_legacy_skills_dest() {
  case "$LLM_PROVIDER" in
    claude) printf '%s/skills/agent-toolkit\n' "${CLAUDE_HOME:-$HOME/.claude}" ;;
    *) return 0 ;;
  esac
}

provider_guidance_dest() {
  case "$LLM_PROVIDER" in
    codex) printf '%s/AGENTS.md\n' "${CODEX_HOME:-$HOME/.codex}" ;;
    claude) printf '%s/CLAUDE.md\n' "${CLAUDE_HOME:-$HOME/.claude}" ;;
  esac
}

provider_skill_is_explicit() {
  [[ "$LLM_PROVIDER" == claude ]] || return 1
  grep -Fxq "$1" "$AGENT_TOOLKIT_HOME/.agents/providers/claude/explicit-only.txt" 2>/dev/null
}

provider_skill_metadata() {
  [[ "$LLM_PROVIDER" == codex ]] || return 0
  printf '%s/.agents/providers/codex/skills/%s/agents/openai.yaml\n' "$AGENT_TOOLKIT_HOME" "$1"
}

# Guidance rendering

source_guidance() { printf '%s/.agents/global/instructions.md\n' "$AGENT_TOOLKIT_HOME"; }
agent_toolkit_start='<!-- agent-toolkit:start -->'
agent_toolkit_end='<!-- agent-toolkit:end -->'
agent_toolkit_notice='<!-- This configuration block is auto-generated by the agent-toolkit repository; manual edits may be overwritten. -->'
concise_output_start='<!-- agent-toolkit:concise-output:start -->'
concise_output_end='<!-- agent-toolkit:concise-output:end -->'
has_concise_output_block() {
  grep -Fxq "$concise_output_start" "$1" && grep -Fxq "$concise_output_end" "$1"
}
update_concise_output_block() {
  local destination=$1 temp
  temp="$(mktemp "${destination}.XXXXXX")"
  cp -p "$destination" "$temp"
  awk -v start="$concise_output_start" -v end="$concise_output_end" '
    $0 == start { in_block = 1; next }
    $0 == end { in_block = 0; next }
    !in_block { print }
  ' "$destination" > "$temp"
  if [[ "$CONCISE_OUTPUT" == true ]]; then
    cat >> "$temp" <<EOF

$concise_output_start
## Concise output

Apply the installed \`concise-output\` skill to all reader-facing responses,
including explanations, reviews, tickets, and documentation.
$concise_output_end
EOF
  fi
  mv "$temp" "$destination"
}
render_guidance_block() {
  local destination=$1 temp
  cp "$(source_guidance)" "$destination"
  update_concise_output_block "$destination"
  temp="$(mktemp "${destination}.XXXXXX")"
  {
    printf '%s\n' "$agent_toolkit_start"
    printf '%s\n\n' "$agent_toolkit_notice"
    cat "$destination"
    printf '\n%s\n' "$agent_toolkit_end"
  } > "$temp"
  mv "$temp" "$destination"
}
strip_guidance_blocks() {
  local destination=$1 temp
  temp="$(mktemp "${destination}.XXXXXX")"
  awk -v guidance_start="$agent_toolkit_start" \
      -v guidance_end="$agent_toolkit_end" \
      -v concise_start="$concise_output_start" \
      -v concise_end="$concise_output_end" '
    $0 == guidance_start || $0 == concise_start { block_depth++; next }
    ($0 == guidance_end || $0 == concise_end) && block_depth > 0 {
      block_depth--
      next
    }
    block_depth == 0 { print }
  ' "$destination" > "$temp"
  mv "$temp" "$destination"
}
append_guidance() {
  local destination=$1 block
  block="$(mktemp "${destination}.XXXXXX")"
  render_guidance_block "$block"
  strip_guidance_blocks "$destination"
  cat "$block" >> "$destination"
  rm -f "$block"
}
render_guidance() { render_guidance_block "$1"; }

# Skill discovery

source_skills() { find "$AGENT_TOOLKIT_HOME/.agents/skills" -mindepth 3 -maxdepth 3 -type f -name SKILL.md -exec dirname {} \; | sort; }
skill_key() {
  local path=$1 prefix="$AGENT_TOOLKIT_HOME/.agents/skills/"
  path=${path#"$prefix"}
  printf '%s\n' "$path"
}
# Ownership and filesystem helpers

resolved_path() {
  local target=$1 link
  link="$(readlink "$target")"
  [[ "$link" == /* ]] && printf '%s/%s\n' "$(cd "$(dirname "$link")" && pwd -P)" "$(basename "$link")" || printf '%s/%s\n' "$(cd "$(dirname "$target")/$(dirname "$link")" && pwd -P)" "$(basename "$link")"
}
owned_marker() { printf '%s/.agent-toolkit-owned\n' "$1"; }
file_hash() { shasum -a 256 "$1" | awk '{print $1}'; }

is_owned_dir() { [[ -f "$(owned_marker "$1")" ]] && grep -qx "$AGENT_TOOLKIT_HOME" "$(owned_marker "$1")"; }
is_user_owned_skill() {
  local source=$1 dest=$2
  [[ -e "$dest" || -L "$dest" ]] || return 1
  if [[ -L "$dest" && "$(resolved_path "$dest")" == "$(cd "$(dirname "$source")" && pwd -P)/$(basename "$source")" ]]; then
    return 1
  fi
  is_owned_dir "$dest" && return 1
  return 0
}
ensure_destination() {
  local target=$1
  if [[ -e "$target" || -L "$target" ]]; then
    if [[ -L "$target" && "$(resolved_path "$target")" == "$2" ]]; then rm "$target"; return; fi
    is_owned_dir "$target" || { echo "Error: refusing to overwrite non-managed path: $target" >&2; return 1; }
  fi
  mkdir -p "$target"
}

# Skill rendering

render_skill() {
  local source=$1 dest=$2 key=$3
  local explicit=no
  if provider_skill_is_explicit "$key"; then
    explicit=yes
  fi
  mkdir -p "$dest"
  if is_owned_dir "$dest"; then
    local old_hash current_hash
    old_hash="$(awk '$1 == "SKILL.md" { print $2 }' "$(owned_marker "$dest")")"
    current_hash="$(file_hash "$dest/SKILL.md" 2>/dev/null || true)"
    [[ -n "$old_hash" && "$old_hash" == "$current_hash" ]] && rm -f "$dest/SKILL.md"
    find "$dest" -type l -delete
    rm -f "$(owned_marker "$dest")"
  fi
  awk -v explicit="$explicit" '
    FNR == 1 && $0 == "---" { print; in_front = 1; next }
    in_front && $0 == "---" { if (explicit == "yes") print "disable-model-invocation: true"; print; in_front = 0; next }
    in_front && $0 ~ /^disable-model-invocation:/ { seen = 1 }
    { print }
    END { if (explicit == "yes" && seen) exit 0 }
  ' "$source/SKILL.md" > "$dest/SKILL.md"
  printf '%s\nSKILL.md %s\n' "$AGENT_TOOLKIT_HOME" "$(file_hash "$dest/SKILL.md")" > "$(owned_marker "$dest")"
  while IFS= read -r file; do
    rel=${file#"$source/"}; [[ "$rel" == SKILL.md ]] && continue
    mkdir -p "$dest/$(dirname "$rel")"
    ln -s "$file" "$dest/$rel"
  done < <(find "$source" -type f ! -name SKILL.md | sort)
  local metadata
  metadata="$(provider_skill_metadata "$key")"
  if [[ -n "$metadata" && -f "$metadata" ]]; then
    mkdir -p "$dest/agents"; ln -s "$metadata" "$dest/agents/openai.yaml"
  fi
}
